### ISSUE TITLE
Why are html files ignored?

### ISSUE THREAD

**Issue by DanielHabenicht** [tolgaerdonmez/handlebars-hot-reload#5]
I was just wondering why it did not auto-reload for html files and wanted to fix it when I came across this: 
https://github.com/tolgaerdonmez/handlebars-hot-reload/blob/9dabbfb29ac908cba995aac75e71198fabe7525a/src/watcher.ts#L6

Any reason why? 
- Can it be removed?
- If not can I add an option to overwrite?

**Comment by tolgaerdonmez** [comment]
Hi, its been a while, I think its because that it is creating html files from handlebars but I'm not sure. I'll look at it and come back. you can also send a PR, any help appreciated :))

**Comment by DanielHabenicht** [comment]
Alright, I will wait till you had a chance to look at it to proceed with an optimal solution. 

I am currently running it with `handlebars-hot-reload -t ./template.html -j ./data.json --outputPath template.out.html` and removed the line, without having any negative side effects.

**Comment by tolgaerdonmez** [comment]
Okay also checked, seems out no problem is caused. Sent a new commit. Thanks for the fix.
